extern const GeoLayout cotmc_area_1_geo[];
extern const GeoLayout cotmc_area_1[];
extern const Collision cotmc_area_1_collision[];
extern const MacroObject cotmc_area_1_macro_objs[];
extern u8 cotmc_dl_Caveice_rgba16[];
extern u8 cotmc_dl_Material5_ci8[];
extern u8 cotmc_dl_Material5_ci8_pal_rgba16[];
extern u8 cotmc_dl_wc_isi_i8[];
extern u8 cotmc_dl_Eisig_rgba16[];
extern u8 cotmc_dl_Material27_ci8[];
extern u8 cotmc_dl_Material27_ci8_pal_rgba16[];
extern u8 cotmc_dl_Material56_ci4[];
extern u8 cotmc_dl_Material56_ci4_pal_rgba16[];
extern u8 cotmc_dl_Water_rgba32[];
extern u8 cotmc_dl_Texture0203_RGB_i8[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_0[513];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_0[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_1[177];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_1[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_2[39];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_2[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_3[20];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_3[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_4[97];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_4[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_5[12];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_5[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_6[261];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_6[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_7[11];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_7[];
extern Gfx mat_cotmc_dl_f3d_material_007[];
extern Gfx mat_cotmc_dl_f3d_material_005[];
extern Gfx mat_revert_cotmc_dl_f3d_material_005[];
extern Gfx mat_cotmc_dl_f3d_material[];
extern Gfx mat_cotmc_dl_f3d_material_008[];
extern Gfx mat_cotmc_dl_f3d_material_006[];
extern Gfx mat_revert_cotmc_dl_f3d_material_006[];
extern Gfx mat_cotmc_dl_f3d_material_003[];
extern Gfx mat_revert_cotmc_dl_f3d_material_003[];
extern Gfx mat_cotmc_dl_f3d_material_004[];
extern Gfx mat_cotmc_dl_f3d_material_001[];
extern Gfx cotmc_dl_Level_mesh_layer_1[];
extern Gfx cotmc_dl_material_revert_render_settings[];
